server:
  port: 8081
spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/next_travel
      auto-index-creation: true

  #This is for eureka client

eureka:
  client:
    register-with-eureka: true #deafult
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true #deafult

# This is for spring activator (we can check mapping and health more... for microservice architecture)
management:
  endpoints:
    web:
      exposure:
        include: "*"
