server:
  port: 8084

spring:
  #This is for datasource
  application:
    name: travel-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/next_travel?createDatabaseIfNotExist=true
    username: root
    password: 1234
  #This is for jpa
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
  #This is for config client
  config:
    import: optional:configserver:http://localhost:8762
  #This is for eureka client

eureka:
  client:
    register-with-eureka: true #deafult
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true #deafult

# This is for spring activator (we can check mapping and health more... for microservice architecture)
management:
  endpoints:
    web:
      exposure:
        include: "*"

